1 Getreide                      2Mehl
2 Mais                          Mehl
3 Reis                          Mehl
4 Zuckerrohr                    Zucker
5 Zuckerruebe                   Zucker
6 Pfeffer                       Pfeffer
7 Flachs                        Flachskleider
8 Baumwolle                     Baumwollkleid
9 Aepfel
10 Citrusfruechte
11 Trauben                      Wein(Wasser,Zucker)
12 Wasser
13 Salz
14 Fisch
15 Bruchholz                    Holzkohle
16 Birkenholz                   Holzkohle,Boote,Gebaeude,Waffen
17 Steineichenholz              Holzkohle,Boote,Gebaeude,Waffen
18 Holzkohle
19 Sandstein                    Gebaeude
20 Granit                       Gebaeude
21 Basalt                       Gebaeude
22 Lehm                         Lehmziegel(2 Lehm,2 Wasser,Sand,Getreide,2 Holzkohle),Tongefaess(Lehm,Wasser)
23 Zement                       Betonziegel(2 Zement,2 Wasser,Sand,Getreide) *Stahl u. Moertel wird benoetigt!!!*
24 Lehmziegel                   Gebaeude
25 Betonziegel                  Gebaeude (mit Stahl u. Moertel)
26 Kalk                         Moertel(Kalk,Wasser,Sand,Zement)
27 Moertel                      Gebaude
28 Schwefel
29 Sand
30 Quarzsand                    Glas(2 SK,2 Quarzsand)
31 Glas                         Gefaess(1 Glas)
32 Leichtleder
33 Leder
34 Schwerleder
35 Knochen
36 leichtes Fell
37 normales Fell
38 dichtes Fell
39 Feder
40 Wurst
41 Mehl
42 Brot
43 Torte
44 Goldmuenze
45 Eisen
46 Stahl
47 Flachskleidung
48 Baumwollwams
49 Seidengewand
50 Steinkohle
51 Bronze
52 Eisenerz
53 Golderz
54 Rohdiamant
55 Huhn
56 Gans
57 Ochse
58 Kuh
59 Wildrind
60 Hausschwein
61 Schaf
62 Ziege
63 Hase
64 Reh
65 Karen
66 Milch
67 Ei
68 Schafswolle
69 Treibstoff
70 Wein
71 Bier
72 Alkohol
73 Proviantpaket
74 Zucker
75 Kaese
76 Boot aus Birke
77 Boot aus Steineiche





Arten von Gebaeuden :


                        Produktions          Mit dieser Qualitaet
Qualitaet    RS    LE   beschleunigung       baubar bis Stufe ...

4           -50%  -50%    -20%                  C
3           -25%  -25%    -10%                  D
2            -     -       -                    E
1           +25%  +25%    +10%                  F
0           +50%  +50%    +20%                  F



Moegliche Baumaterialien


Kennungszahlen         4         3             2                 1            0
Gebiet
Grundkonstruktion(GK)  Bruchholz Knochen       Holz              Metall     Stahl
Mauer            (M)   Leder     Holz          Stein             Ziegel     Beton

Diese Tabelle spiegelt die Qualitaet des Gebaeudes wieder.
Die Endzahl ergibt sich aus
Wurzel von (GK*GK+M*M)/2

Wenn sie z.B. ein Knochen-Beton Gebaeude bauen wollen ergibt sich hierfuer
Wurzel von (3*3+0*0)/2
und das ist Wurzel von 4.5 also ungefaehr 2
Also bringt eine Betonkonstruktion die auf keinem Stahl gebaut ist wenig.


Und hier die komplette Tabelle

           Leder       Holz       Stein       Ziegel      Beton
Bruchholz    4          4           3           3           3
Knochen      4          3           3           3           2
Holz         3          3           3           2           1
Metall       3          3           2           1           1
Stahl        3          2           1           1           0


Wetterbonus : 
Ihre Leute koennen am besten in einem milden Klima arbeiten in dem es sehr
trocken ist. Sollte das Klima anders sein gilt folgende Tabelle

            Produktionsgeschwindigkeitsmalus

nass        -75%    
feucht      -50%
normal      -25%
trocken     -10%

heiss       -50%
warm        -25%
kalt        -25%
eisig       -50%

Um dem Gegenzuwirken baut man Gebaeude um die Produktionsstaetten. 
Jede Gebaeudeart schuetzt vor Kaelte,Hitze und Feuchtigkeit unterschiedlich.

Die Angabe bei den Rohstoffen muss mit der Ausbaustufe des Gebaeudes multipliziert werden.
                                                                                     Vorteile
                                                                                     (  LE/RS/Hitze/Kaelte/Feuchtigkeit/)
1 Lederhuette     10 Knochen                            20 Leichtleder                150/ 3/ +20%/  +10%/+15%
2 Lederhaus       10 Knochen                            20 Schwerleder                250/ 5/ +10%/  +20%/+20%
3 Holzhuette      20 Birkenholz                         25 Birkenholz                 500/ 8/ +25%/  +25%/+25%
4 Holzhaus        20 Steineichenholz                    25 Steineichenholz            800/12/ +20%/  +25%/+35%
5 Steinhuette     25 Birkenholz                         30 Granit(,Glas*)            1200/20/ +30%/  +20%/+40%
6 Steinhaus       25 Steineichenholz                    30 Granit(,Glas*)            1500/20/ +30%/  +20%/+50%
7 Basaltfeste     30 Steineichenholz                    35 Basalt                    1600/25/ +35%/  +25%/+50%  wirkt Antimagisch
8 Ziegelhuette    30 Birkenholz                         30 Ziegel,10 Moertel(,Glas*) 2500/30/ +40%/  +30%/+55%
9 Ziegelhaus      30 Steineichenholz                    30 Ziegel,15 Moertel(,Glas*) 3000/30/ +40%/  +30%/+65%
* Glasfenster                         15 Glas                                        -500/-2/ -10%/  +10%/+/-0%





Wohnhaeuser:

Sie koennen Wohnhaeuser in mehreren Groessen- und Hoehenstufen bauen.
Ausserdem koennen sie die "Zimmeranzahl" bestimmen, also wieviele Familien/Leute
einziehen koennen. Je weniger Zimmer sie in einem Haus bauen, desto mehr kostet
ein Zimmer. Dann werden weniger arme Leute in das Haus einziehen.
Einzelne Personen oder Paare ohne Kinder brauchen 1 Zimmer
Familien mit 1-2 Kindern brauchen 2 Zimmer
Familien mit 3-4 Kindern brauchen 3 Zimmer
Familien mit 5-6 Kindern brauchen 4 Zimmer
Familien mit 7-8 Kindern brauchen 5 Zimmer
Familien mit 9-10 Kindern brauchen 6 Zimmer

Wenn sie also ein Haus mit Zimmeranzahl 1 bestimmen,einer Groessenstufe 4 und einer Hoehenstufe 4
so wird es lange dauern bis jemand einzieht ... (nur ein seeehr reicher Aussenseiter)
Sollten sie so ein Haus bauen muessen sie wohl oder uebel die Zimmerzahl
erhoehen (Kostet ein wenig-Zimmereinrichtungen muessen geaendert werden).

"Aufwertungen" von den Wohnhaeusern:

Qualitaet            Leder    Holz   Stein    Ziegel

max. Zimmeranzahl:    2         4     12       25
max. Hoehenstufe:     1         2      3       4
max. Groessenstufe:  3*2      3*2     4*3     5*4


                     Anzahl der max. Zimmer je Stockwerk
Groessenstufen      Leder   Holz     Stein   Ziegel

1                   1       1        1       1
2                   1       1        1       2
4                   1       2        2       3
6                   2       2        3       4
8                   -       -        4       6
9                   -       -        5       7
12                  -       -        6       9
16                  -       -        -      12
20                  -       -        -      15

Also koennen in einem Ziegelhaus der Groesse 20 mit 4 Stockwerken 60
einzelne Leute oder 10 Grossfamilien wohnen. Die Qualitaet der Wohnstube
waere 1. Qualitaetsstufe 6 waere erreicht, wenn nur 2 Leute darin wohnen
wuerden. Der Preis waere dann immens : 36*hoeher!
Fuer einen Koenig gerade genug.

Dazu kommen dann noch die Moebel. Je groesser ein Zimmer desto mehr Moebel
werden benoetigt. Moebel werden immer dann gekauft, wenn man umzieht.

Unterhaltung der Zimmer :

- Zimmergroesse (Also Groessenstufe*Etagen/Zimmer)*2= Anzahl der zu kaufenden
  Moebel bei Neueinzug.
- Pro Zimmer wird jeden Monat natuerlich Miete faellig.
- Pro Zimmer wird ausserdem noch 1*Kleidung pro Monat gekauft. Die Qualitaet
  haengt vom Kaeufer ab.

>>>> Wenn sie die Moebelpreise senken, koennen sich mehr Leute einen Umzug
leisten. Wenn die Bevoelkerung sehr arm ist, und sie Grosse Haeuser mit
kleinen Zimmern gebaut haben, ist eine Senkung der Preise sehr sinnvoll
*Leute ziehen schon bei geringeren Ersparnissen um*

>>>> Ist genau der Gegenteil der Fall (Also sie haben grosse Zimmer) so
bringt eine Erhoehung Vorteile wie Nachteile :
-> Die armen Leute koennen nicht mehr umziehen und verarmen noch mehr.
-> Die etwas reicheren bleiben in ihren Luxusvillen.
-> Neue Leute (Wachstum!) koennen sich keine Wohnung leisten und landen auf
der Strasse.






Ziegelhaeuser:






"Aufwertungen" von den Wohnhaeusern:

Qualitaet  Leder                    Holz                   Stein                   Ziegel

1          LederZelt                Holzbaracke            Steinhuette/Steinhaus
2          LederHuette/Haus         HolzHuette/Haus
3                                   Grosse HolzHuette/Haus
4
5
6

* Mit Glas Erhoeht sich der Kaeltebonus um 25%!




