







                        Trinken   >> Brunnen      \\\\ Verdursten >>Tod
                        Essen     >> Marktplatz   \\\\ Verhungern >>Tod
                        Kleidung  >> Marktplatz   \\\\ Absinken der Charisma >> Keine neue Arbeit/Entlassung >> Kein Geld >> Kriminell
                        Schmuck   >> Marktplatz   >> Erhoehung der Charisma
                      Vergnuegung >> Vergnuegungsgebaeude
                        Tempel    >> Tempel
                        *Miete    >> Wohnungsamt
              Arbeiter bezahlen   >> Arbeitsgebaeude
              den Armen geben     >> Stadt

Einkommen der Leute
                                     - Gebaeude bauen (Investitionen)
                       Ersparnisse > - Moebel fuer Wohnung kaufen


Ereignisse im Leben eines Leutchens passieren bei Auffeinandertreffen mit
einem Zweiten in der Stadt :

- Straftat (Diebstahl,Mord etc.)
- Anstellung als Arbeiter
- Zum Mann/zur Frau nehmen






