Wie wird das Wetter?

Wettertabellen und Regeln

1. Waerme

Die Waerme beeinflusst die Verdunstung, das Pflanzenwachstum und behindert
u.u. die Arbeit. Waerme ist (durch die Verdunstung) fuer die Wolkenbildung
gut.


Faktoren zur Ermittlung der Waerme in einem Gebiet.







                          /Breitengrad
       /Sonneneinstrahlung-Schraege der Ebene
                          \Sonnenstaerke *Startparameter*
                          \Schatten

                         /Bodenart
Waerme -Waermespeicherung-Luftwaerme *Gebiet erhoeht Luftwaerme der Umgebung*




