Abkuerzungen:

WS - Wasser
HK - Holzkohle
SK - Steinkohle
TR - Treibstoff

Name       Verbesserung(ben. Zusatzstoffe)                              Wert            Verwendung

Bruchholz      -                                                        1/8 Holzkohle   Verbrennung
Birkenholz     1/2 Holzkohle                                            1/4 Holzkohle   ",H/W/SBAU
Steineiche     Holzkohle                                                1/2 Holzkohle   ",H/W/SBAU
Sandstein      >>BAU                                                    1/2 Stein       StrBAU
Granit         >>BAU                                                    1 Stein
Basalt         >>BAU                                                    1 Stein
Steinkohle     >>ENERGIE                                                1 Kohle
Oel            Treibstoff(1SK)                                          2 Kohle
Bronze         >>SCHMIED                                                1 Eisen
Eisenerz       Eisen(2HK)
*Meteoreisen   Meteorstahl(2TR)
*Arkanium      Arkaniumstahl(2TR)
*Endurium      Enduriumstahl(4TR)
*Titanium      Titaniumstahl(8TR)
Silbererz      Silbermuenze(2HK)
Golderz        Goldmuenze(1SK)
Platinerz      Platinmuenze(2SK)
Weizen         Mehl
Reis           Mehl
Mais           Mehl
Fruechte       Alkohol(Zucker)
Gemuese        Alkohol(Zucker)
Fisch          -
Wasser         *
Baumwolle      >>Schneider
Flachs         >>Schneider
Seide          >>Schneider
Zement         Ziegel(Sand,WS)
Kalk           Moertel(Mehl,WS)
Sand           *
Quarzsand      Glas(2SK)
Schwefel       Brennbare Substanz(Alkohol,Oel)
Salz           *
Pfeffer        -
Zuckerror      Zucker(2WS,1HK)
Zuckerruebe    Zucker(2WS,1HK)
Hausschwein    2Fleisch,1SchweinLeder,1Knochen{SCHLACHTUNG}
Schaf          1Fleisch,2SWolle,1Knochen{SCHLACHTUNG}/1Milch
Auerochse      4Fleisch,2SchwereLeder,2Knochen{SCHLACHTUNG}/2Milch
Holzkohle      >>ENERGIE
Treibstoff     >>ENERGIE
Eisen          Stahl(2SK),>>SCHMIED
*Meteorstahl   >>SCHMIED
*Arkaniumstahl >>SCHMIED
*Enduriumstahl >>SCHMIED
*Titaniumstahl >>SCHMIED
Mehl           Brot(WS,Salz,1/2HK)
Alkohol        Wein(Fruechte,WS)/Bier(Mehl,WS)
Ziegel         >>BAU
Moertel        >>BAU
Glas           >>BAU,>>WERKZEUGMACHER
Brn. Substanz  >>ZAUBERZUNFT
Brot           Torte(Milch,Zucker,Fruechte)
Fleisch        Wurst(Salz,Pfeffer)
Knochen        >>SCHMIED
Milch          *



Gebaeude und Unterhaltung
                                                                 Produktions-
Klasse   Holz   Granit  Ziegel  Moertel Stahl   Glas     Gold    Nahrung Bauzeit Faktor
|  A  |  25*  |  20*  |   -   |   -    | 3    |  -      | -    |   -    |   5   |  1   |
|  B  |  45   |  30   |   -   |   -    | 5    |  -      | 10*  |   -    |  10   |  3   |
|  C  |  65   |  40   |  20*  |  10*   | 8    |  -      | 25   |   -    |  16   |  5   |
|  D  |  90   |  60   |  40   |  20    | 40*  |  -      | 50   |   -    |  28   | 12   |
|  E  |  120  |  80   |  75   |  35    | 70   | 25*     | 75   |   -    |  42   | 28   |
|  F  |  150  |  100  |  100  |  50    | 100  | 50      | 100  |   -    |  55   | 64   |

Und hier die Restaurationskosten.
Waehrrend der Restauration kann NICHT gearbeitet werden (Es muss auch kein
Unterhalt bezahlt werden.

Klasse   Holz   Granit  Ziegel Moertel  Stahl   Glas    Gold    Nahrung Bauzeit
|  A  |  10   |  4    |   -   |   -   |  3     |  -    |  -    |   5    |   1   |
|  B  |  15   |  6    |   -   |   -   |  5     |  -    |  10   |   10   |   1   |
|  C  |  25   |  8    |  2    |  1    |  8     |  -    |  25   |   20   |   2   |
|  D  |  30   |  12   |  4    |  2    | 17     |  -    |  50   |   30   |   2   |
|  E  |  40   |  16   |  6    |  3    | 40     |  15   |  75   |   45   |   3   |
|  F  |  60   |  20   |  10   |  5    | 70     |  30   |  100  |   60   |   3   |




