Das Waffenschmieden




Hier die haeufigsten Arten um reine Eisenwaffen zu schmieden:

                                    Kommentar
-Die Gusstechnik        - "Schnell und billig aber schlecht ..."
-Die Reineisentechnik   - "Die Schwerter werden sehr sehr biegsam ..."
-Die Lehmbacktechnik    - "Gut und schnell, aber der Lehm ist eine hohe Fehlerquelle ..."
-Die Flaemmtechnik      - "Sehr gut. Die Qualitaet steigt mit jedem "Durchgang" ..."
-Die Feilspaenentechnik - "Die derzeit beste Qualtitaet - wenn man lange warten kann ..."



a) Hiermit kann man schnell und billig eine grosse Menge an Schwertern
zusammenstellen: Das fluessige Eisen wird einfach in eine Form gegossen,
abgekuehlt und das fertige Schwert herausgenommen ... um dann zu erkennen,
dass die Schwerter in der Schlacht wie Glas zersplittern ...

Geschwindigkeit: 4 Produktionseinheiten in 1 Zeiteinheit
Qualitaet: BF+50, -2 TP

b) Eine Eisenstange erhitzt und mit viel Ausdauer und Kraft bearbeitet,
anschliessend mit Schleifstein mit einer Schneide versehen - Fertig ist
ein biegsames Schwert ...

Geschwindigkeit: 2 Produktionseinheiten in 1 Zeiteinheit
Qualitaet: BF+35 -1 TP


c) Die Lehmbacktechnik

Bei dieser Technik wird die Klinke mit Ausnahme der Schneiden und der Spitze
mit Lehm bestrichen und im Feuer erhitzt, dannach in Fluessigkeit
abgeschreckt. Die fertige Klinge ist dann am Rand hart und fest, in der
Mitte dagegen biegsam und federnd.
Das klingt gut, jedoch muss beachtet werden, dass durch fehlerhaftes
Auftragen das Schwert unbrauchbar wird.

Geschwindigkeit: 1 Produktionseinheit in 2 Zeiteinheiten
Qualitaet: BF    (zu 10% Fehler. Dann Schwert siehe b))

d) Die Flaemmtechnik

Mehrere Stahl-(!) und Eisenstaebe, die einen fuer Haerte die anderen
fuer Biegsamkeit, werden zusammengelegt und geschmiedet zu einer flachen
Klinge. Anschliessend verdreht man sie schraubenartig gegeneinander und
schmiedet sie erneut zu einer flachen Klinge. Man wiederholt diese Prozedur
mehrere Male, um sie dadurch vollkommen zu verbinden, so dass sie sich
ergaenzen.

Geschwindigkeit: 1 Produktionseinheit in 16 Zeiteinheiten
Qualitaet: BF-50

e) Die Feilspaentechnik

... ist die langwierigste Technik die wir kennen. Das Schwert wird erst wie
bei d) geschmiedet (am besten aus magischen Metallen). Dannach wird es zu
winzigen Feilspaenen zerkleinert, mit tierischen Abfaellen vermengt, dann
gereinigt, erneut zusammengebacken und zu einem Schwert schmieden, das ein
weiteres Mal zerfeilt wird.

Geschwindigkeit: 1 Produktionseinheit in 128 ZE
Qualitaet: BF-100; TP+3;







Der Bruchfaktor

Der Bruchfaktor zeigt an, wie lange die Waffe (oder Ruestung) noch einsatzbereit ist.
Der Bruchfaktor kann zwischen -100 (praktisch unzerstoerbar) bis 100 (zerstoert)
schwanken.
Waffen werden durch spezielle Manoever, Attacken oder Paraden aber auch durch
Wind und Wetter oder auch einfach durch Benutzung beschaedigt oder gar
zerstoert.




a) Waffe gegen Waffe

Wenn der Angreifer bei seiner gelungenen Attacke die selbe Zahl wuerfelt wie
der Verteidiger bei seiner gelungenen Parade, kommt es zu einem Bruchtest.
Beide muessen mit einem W20 ermitteln, ob die Waffe bricht.
Das geschieht wenn der Wurf unter dem BF liegt. Ansonsten steigt der BF
der Waffe um 1.

b) Waffe gegen Ruestung

Sobald bei einem direkten Angriff (Nahkampf) die Waffe keinen Schaden
anrichtet (!Nur wenn der Angreifer getroffen hat!), wird ebenfalls ein
Bruchtest durchgefuehrt.

c) Ruestung gegen Waffe

Ruestungen haben eine andere Art von